fix purging wireshark-common when removing wireshark system group fails
git-svn-id: svn://svn.debian.org/svn/collab-maint/ext-maint/wireshark/trunk@15604 19660600-52fe-0310-9875-adc0d7a7b53c

diff --git a/debian/wireshark-common.postrm b/debian/wireshark-common.postrm
--- a/debian/wireshark-common.postrm
+++ b/debian/wireshark-common.postrm
@@ -5,7 +5,8 @@ GROUP=wireshark
 if [ "$1" = "purge" ] ; then
       if getent group $GROUP >/dev/null; then
                 if [ -x /usr/sbin/delgroup ]; then
-                        delgroup --system $GROUP
+                        echo "Removing wireshark group..."
+                        delgroup --system $GROUP || echo "Could not remove wireshark group."
                 fi
         fi
 fi
