falling back to setting set-user-id bit if using Linux Capabilities fails
git-svn-id: svn://svn.debian.org/svn/collab-maint/ext-maint/wireshark/trunk@15487 19660600-52fe-0310-9875-adc0d7a7b53c

diff --git a/debian/wireshark-common.postinst b/debian/wireshark-common.postinst
--- a/debian/wireshark-common.postinst
+++ b/debian/wireshark-common.postinst
@@ -17,9 +17,13 @@ if [ -e "$PROGRAM" ]; then
             ! /usr/sbin/dpkg-statoverride --list $PROGRAM >/dev/null; then
             addgroup --quiet --system $GROUP
             chown root:$GROUP $PROGRAM
-            if which /sbin/setcap > /dev/null ; then
+            if which setcap > /dev/null ; then
                 chmod u=rwx,g=rx,o=r $PROGRAM
-                setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap
+                if ! setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap; then
+                    echo "Setting capabilities for dumpcap using Linux Capabilities failed."
+                    echo "Falling back to setting set-user-id bit."
+                    chmod u=rwxs,g=rx,o=r $PROGRAM
+                fi
             else
                 chmod u=rwxs,g=rx,o=r $PROGRAM
             fi
