warn administrator during configuring dumpcap to allow non-root users to capture packets if creating the wireshark system group fails
git-svn-id: svn://svn.debian.org/svn/collab-maint/ext-maint/wireshark/trunk@24240 19660600-52fe-0310-9875-adc0d7a7b53c

diff --git a/debian/wireshark-common.postinst b/debian/wireshark-common.postinst
--- a/debian/wireshark-common.postinst
+++ b/debian/wireshark-common.postinst
@@ -13,7 +13,12 @@ if ! dpkg-statoverride --list $PROGRAM > /dev/null; then
 	    chown root:root $PROGRAM
 	    chmod u=rwx,go=rx $PROGRAM
 	else
-	    addgroup --quiet --system $GROUP
+	    if ! addgroup --quiet --system $GROUP; then
+		echo "Executing \"addgroup --quiet --system $GROUP\" failed."
+		echo "Most probably the $GROUP group exists, but is not a system group."
+		echo "Please delete the existing group or re-create it as a system group and try configuring wireshark-common again."
+		exit 1
+	    fi
 	    chown root:$GROUP $PROGRAM
 	    if which setcap > /dev/null ; then
                 chmod u=rwx,g=rx,o=r $PROGRAM
